Repository ianstormtaylor/superstruct, pull requests merged in 2021-02, with the labels that each got.

#651 docs: replaced deprecated with current API use in introduction docs
  docs/readme.md
Labels: docs

#534 Add type deprecated
  .eslintrc
  docs/reference/utilities.md
  src/structs/utilities.ts
  test/index.ts
  test/typings/deprecated.ts
  test/validation/deprecated/invalid-null.ts
  test/validation/deprecated/invalid-property.ts
  test/validation/deprecated/invalid.ts
  test/validation/deprecated/valid-property.ts
  test/validation/deprecated/valid-undefined.ts
  test/validation/deprecated/valid.ts
Labels: feature

#639 fix: fixed describe for some literal types
  src/structs/types.ts
  src/utils.ts
  test/typings/describe.ts
Labels: bug
