Repository ianstormtaylor/superstruct, pull requests merged in 2022-09, with the labels that each got.

#1106 Stop coercing empty optional fields to undefined values
  src/utils.ts
  test/api/create.ts
Labels: improvement

#1112 Support Node 14 (again)
  .github/workflows/ci.yml
  config/rollup.js
  package.json
Labels: bug

#1113 Document custom error messages for refinements
  docs/reference/refinements.md
Labels: docs
